############################
## CHANGE THESE
############################

baseURL: "https://elisa-qb.github.io/website"
title: Elisa Ferrari (she/her)

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
